
project:
  type: website

website:
  title: "대학사용법 2.0"
  navbar:
    left:
      - href: index.qmd
        text: 소개
      - href: toc.qmd
        text: 목차 
      - href: license.qmd
        text: 라이선스

format:
  html:
    lang: ko
    theme: cosmo
    toc: true
    toc-location: left
