
project:
  type: website
  output-dir: _site

website:
  title: "대학사용법 2.0"
  navbar:
    left:
      - href: index.qmd
        text: 소개
      - href: toc.qmd
        text: 개정판 목차 
      - href: 10_principles.qmd
        text: 대학생활 필수지침 10가지  
      - href: license.qmd
        text: 라이선스

format:
  html:
    lang: ko
    theme: cosmo
    toc: true
    toc-location: left
