---
title: "개정판 목차 정리"
author: 
  name: "김재연"
  url: https://jaeyk.github.io
format:
  html:
    theme: cosmo
    css: styles.css
date: today
---

- 개정판 프롤로그  
  - 대학이라는 바다를 항해하는 이들에게 다시 말을 건넨다  
  
- check! 기회의 선순환’을 만들기 위한 대학생활 위한 필수지침 10가지  

## Part 1. 고등학생은 입시를, 대학생은 인생을 준비한다 (대학탐색)
- “관점을 바꿔야 기회의 문이 열린다”
1. 대학에서는 교육이 아니라 학습을 한다  
2. 이제 고등학생의 삶과 결별하라  
   - 교육받는 대학생 A vs 학습하는 대학생 B  
3. 대학에서는 나만의 대학사용법이 필요하다  

## Part 2. 대학, 다니지 말고 고용하라 (공부탐색)
- “배움이 곧 기회다”
4. 학습 포트폴리오가 대학생활의 질을 결정한다  
5. Read wide & Think deep 학습전략법  
   - Tip 1: 대학생의 독서법  
   - Tip 2: 자료조사법  
   - Tip 3: 인공지능 시대에 학습력을 키우는 세 가지 원칙  
   - Tip 4: 전공마다 다른 학습법이 필요하다  
   - Tip 5: 학문 간 소통은 선택이 아니라 필수다  
   - Tip 6: 학습지원시설 이용하기  
   - Tip 7: 교수 오피스 아워 활용법  
6. 어학은 기본 체력이다  
7. 소통능력이 떨어지면 전문성을 인정받을 수 없다  
   - Tip 8: 사고력을 키우는 생각훈련법  
   - Tip 9: 미국 박사과정 진학을 위한 학업계획서(SOP) 쓰는 법  
   - Tip 10: 슬라이드덱을 잘 만드는 방법  
8. 전문가가 되려면 비판적 사고력은 필수다  
   - check!: 비판적 사고력 신장을 위한 3단계 훈련법  
9. 성장형 마인드셋을 선택하라  
   - 고정형 마인드셋 vs 성장형 마인드셋  

## Part 3. 스펙을 쌓지 말고 커리어를 키워라 (진로탐색)
- “경험의 양이 아니라 질이 기회를 만든다”
10. 커리어란 개성을 경쟁력으로 만드는 것이다  
    - Tip 11: 교환학생이 고려해야 할 것들  
    - Tip 12: 방학을 잘 활용하는 법  
11. 다양한 사람을 만나면 다양한 기회가 온다  
12. 다른 사람에게 조언을 구하는 법  
    - Tip 13: 비즈니스 이메일 쓰는 법  
    - Tip 14: 인포메이션 인터뷰 질문법  
13. 스펙과 커리어는 같지 않다  
14. 직장과 커리어는 다르다  
15. 4학년, 이제는 더하지 말고 빼라  
    - Tip 15: 채용 인터뷰 준비법  
    - Tip 16: 유학에도 목적이 다르다  
    - check!: 방황에 마침표를 찍기 위한 Q & A  
16. 기회의 선순환: 때로는 기다리고, 때로는 도전하라  
    - check!: 학년별 학습 로드맵: 기회의 선순환을 설계하자  
    - Tip 17: 체력이 곧 자신감이다 — 공부와 삶의 지속력을 위하여  

## Part 4. 태도가 운명을 바꾼다 (인생탐색)
- “태도는 기회의 어머니다”
17. 꿈보다 태도가 삶을 지배한다  
18. 나의 기준을 지키는 것이 실력이다  
19. 타인의 기준을 지키는 것이 인격이다  
20. 우리의 기준을 지키는 것이 리더십이다  

- 에필로그
